server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: USER-SERVICE


management:
  zipkin:
    base-url: http://localhost:9411/api/v2/spans

  sleuth:
    sampler:
      probability: 1.0
