server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: ORDER-SERVICE


eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka
