server:
  port: 8761


eureka:
  instance:
    hostname: local
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka/


management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  tracing:
    sample:
      probability: 1.0

