server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: PRODUCT-SERVICE


  eureka:
    client:
      service-url:
        default-zone: http://eureka:password@localhost:8761/eureka
