server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: INVENTORY-SERVICE


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  tracing:
    sample:
      probability: 1.0





