server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: INVENTORY-SERVICE


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka



